%Script for plotting logfiles generated by result.m
 % load a logfile and then run this script to plot the contents

DCATime        = [LogsDCA.time];
BDCA_AdaptTime = [LogsBDCA_adapt.time];

DCAIter        = [LogsDCA.totaliter];
BDCA_AdaptIter = [LogsBDCA_adapt.totaliter];

N = length(DCATime);

figure()
plot(DCATime./BDCA_AdaptTime,'kx','MarkerFaceColor','r','MarkerSize',8)
hold on
p2 = plot(ones(1,N)*mean(DCATime./BDCA_AdaptTime),'b-.');
hold off
xlabel('Run')
ylabel('Time Ratio')
title('DCA/BDCA')
fontsize(15,'points');
legend(p2,{'Average Time Ratio'});

figure()
plot(DCAIter./BDCA_AdaptIter,'kx','MarkerFaceColor','r','MarkerSize',8)
hold on
p4 = plot(ones(1,N)*mean(DCAIter./BDCA_AdaptIter),'b-.');
hold off
xlabel('Run')
ylabel('Iteration Ratio')
title('DCA/BDCA')
fontsize(15,'points');
legend(p4,{'Average Iteration Ratio'});
