%Script for plotting logfiles generated by skipping_result.m

avgDCAtime     = mean([LogsDCA.time]);
avgDCAiter     = mean([LogsDCA.totaliter]);

numskipvals    = length(SkipLogs);

avgBDCAtime    = zeros(numskipvals,1);
avgBDCAiter    = zeros(numskipvals,1);
skipvals       = zeros(numskipvals,1);


for i = 1:numskipvals
    avgBDCAtime(i)  = mean([SkipLogs{i}.LogsBDCA_adapt.time]);
    avgBDCAiter(i)  = mean([SkipLogs{i}.LogsBDCA_adapt.totaliter]);
    skipvals(i)     = SkipLogs{i}.lambdaskip;
end

figure()
plot(skipvals,avgDCAtime./avgBDCAtime,'kx','MarkerFaceColor','r','MarkerSize',8)
xlabel('$\lambda$ skip','Interpreter','latex')
ylabel('DCA/BDCA Time Ratio')
fontsize(15,'points');


figure()
plot(skipvals,avgDCAiter./avgBDCAiter,'kx','MarkerFaceColor','r','MarkerSize',8)
xlabel('$\lambda$ skip','Interpreter','latex')
ylabel('DCA/BDCA Iteration Ratio')
fontsize(15,'points');